measurement_info:
  measurement_id: example-tpx3-unpacking
  run_number: 1

environment:
  working_dir: data/examples/analysis/unpacker

analysis:
  mode: hermes
  unpacker_program:
    name: tpx3-spidr-cpp
    executable_path: build/backends/tpx3-spidr/hermes-tpx3-spidr
  analysis_directory: data/examples/analysis/unpacker/analysis
  tpx3_files:
    - path: tests/data/Example_1kHz_5frames.tpx3
