max_time_spread_ticks: 491520
min_cluster_size: 2
max_cluster_size: 64
min_pixel_tot_raw: 1
min_cluster_tot_raw: 2
max_cluster_tot_raw: 65472
max_aspect_ratio: 3.0
min_filled_fraction: 0.5
adjacency: 8
