measurement_info:
  measurement_id: example-tpx3-timewalk-calibration
  run: timewalk-cal

environment:
  working_directory: data/examples/analysis/timewalk_calibration
  analysis_directory: analysis

analysis:
  mode: hermes
  unpacking:
    program:
      name: tpx3-spidr-cpp
      executable_path: build/backends/tpx3-spidr/hermes-tpx3-spidr
    tpx3_files:
      - path: tests/data/Example_1kHz_5frames.tpx3
