measurement_info:
  measurement_id: example-tpx3-two-stage-analysis
  run_number: 1

environment:
  working_dir: data/examples/analysis/two_stage

analysis:
  mode: hermes
  unpacker_program:
    name: tpx3-spidr-cpp
    executable_path: build/backends/tpx3-spidr/hermes-tpx3-spidr
  analysis_directory: data/examples/analysis/two_stage/analysis
  tpx3_files:
    - path: tests/data/Example_1kHz_5frames.tpx3
  photon_reconstruction:
    program:
      name: photon-clusterer-cpp
      executable_path: build/backends/photon-clusterer/hermes-photon-clusterer
    pixel_data_directory: data/examples/analysis/two_stage/analysis/pixelHits
    photon_output_directory: data/examples/analysis/two_stage/analysis/photons
    clustering_algorithm: connected_components
    settings:
      max_time_spread_ticks: 491520
      min_cluster_size: 2
      max_cluster_size: 64
      min_pixel_tot_raw: 1
      min_cluster_tot_raw: 2
      max_cluster_tot_raw: 65472
      max_aspect_ratio: 3.0
      min_filled_fraction: 0.5
      adjacency: 8
      position_averaging: arithmetic
      photon_time_estimator: leading_edge
      timewalk_calibration_file: calibrations/tpx3/time-walk_example.json
      save_photon_pixels: true
